export interface ThemeDefinition {
  id: number;
  name: string;
  category: string;
  primary: string; // Hex
  primaryHover: string;
  secondary: string;
  accent: string;
  badgeBg: string;
  badgeText: string;
  gradient: string;
  previewColor: string;
}

export const OFFICIAL_WHATSAPP_URL = "https://wa.me/22570501356";
export const OFFICIAL_WHATSAPP_NUMBER = "+225 70 50 13 56";

// Formules d'abonnement Wave Côte d'Ivoire (Règlement manuel, aucune API de paiement)
export const WAVE_PAY_COUPLE_URL = "https://pay.wave.com/m/M_W9fOyOGfFiNN/c/ci/?amount=3000";
export const WAVE_PAY_INDIVIDUAL_URL = "https://pay.wave.com/m/M_W9fOyOGfFiNN/c/ci/?amount=2000";

// Conservé pour compatibilité avec les anciens écrans
export const OFFICIAL_WAVE_PAY_URL = WAVE_PAY_INDIVIDUAL_URL;

export const PRICING_PLANS = [
  {
    id: "couple",
    name: "Formule Couple",
    amount: 3000,
    payUrl: WAVE_PAY_COUPLE_URL,
    tagline: "Accès complet pour les deux partenaires",
    description:
      "Un seul règlement de 3 000 FCFA ouvre l'espace partagé aux deux fiancés. Chacun se connecte depuis son propre téléphone avec le code d'accès unique du couple et son adresse email.",
    features: [
      "Accès simultané pour les deux partenaires",
      "Un code d'accès unique généré automatiquement",
      "Connexion par email personnel de chaque conjoint",
      "Synchronisation instantanée sur deux appareils",
      "Tous les modules et jeux sans restriction",
    ],
    isRecommended: true,
  },
  {
    id: "individual",
    name: "Formule Individuelle",
    amount: 2000,
    payUrl: WAVE_PAY_INDIVIDUAL_URL,
    tagline: "Accès personnel pour un seul partenaire",
    description:
      "Règlement de 2 000 FCFA donnant un accès personnel complet à l'espace de préparation. Le second partenaire pourra être ajouté ultérieurement en passant à la Formule Couple.",
    features: [
      "Accès individuel complet",
      "Code d'accès personnel unique",
      "Connexion par votre adresse email",
      "Tous les modules de préparation",
      "Évolution possible vers la Formule Couple",
    ],
    isRecommended: false,
  },
];

export const APP_NAME = "Wedding Mood";
export const APP_TAGLINE = "Application premium de préparation au mariage pour jeunes couples chrétiens en Côte d'Ivoire";

// 20 Beautiful Color Themes
export const COLOR_THEMES: ThemeDefinition[] = [
  {
    id: 1,
    name: "Terracotta Royal (Par défaut)",
    category: "Chaleur & Tradition",
    primary: "#C05638",
    primaryHover: "#A84429",
    secondary: "#1E3A2F",
    accent: "#D4AF37",
    badgeBg: "#FDF4EE",
    badgeText: "#C05638",
    gradient: "from-[#C05638] via-[#D4AF37] to-[#1E3A2F]",
    previewColor: "#C05638",
  },
  {
    id: 2,
    name: "Ivoire Céleste & Or",
    category: "Lumière & Noblesse",
    primary: "#B8860B",
    primaryHover: "#996F08",
    secondary: "#2C3E50",
    accent: "#E5C158",
    badgeBg: "#FFFDF0",
    badgeText: "#996F08",
    gradient: "from-[#B8860B] via-[#E5C158] to-[#2C3E50]",
    previewColor: "#B8860B",
  },
  {
    id: 3,
    name: "Émeraude Éternelle",
    category: "Élégance Sacrée",
    primary: "#145A32",
    primaryHover: "#0E3E22",
    secondary: "#C05638",
    accent: "#C59B27",
    badgeBg: "#EAF5EE",
    badgeText: "#145A32",
    gradient: "from-[#145A32] via-[#27AE60] to-[#C59B27]",
    previewColor: "#145A32",
  },
  {
    id: 4,
    name: "Or d'Abidjan",
    category: "Prestige Ivoirien",
    primary: "#A37A2C",
    primaryHover: "#846220",
    secondary: "#1B2A38",
    accent: "#E8C872",
    badgeBg: "#FAF6EC",
    badgeText: "#846220",
    gradient: "from-[#A37A2C] via-[#E8C872] to-[#1B2A38]",
    previewColor: "#A37A2C",
  },
  {
    id: 5,
    name: "Rose Poudré & Champagne",
    category: "Douceur Romantique",
    primary: "#A65B6F",
    primaryHover: "#8E465A",
    secondary: "#34495E",
    accent: "#D9A066",
    badgeBg: "#FCF3F5",
    badgeText: "#A65B6F",
    gradient: "from-[#A65B6F] via-[#F5D5CE] to-[#34495E]",
    previewColor: "#A65B6F",
  },
  {
    id: 6,
    name: "Bleu Nuit Majestueux",
    category: "Sérénité & Foi",
    primary: "#1B3B6F",
    primaryHover: "#132A50",
    secondary: "#C05638",
    accent: "#E0A96D",
    badgeBg: "#EEF4FC",
    badgeText: "#1B3B6F",
    gradient: "from-[#1B3B6F] via-[#4A6FA5] to-[#E0A96D]",
    previewColor: "#1B3B6F",
  },
  {
    id: 7,
    name: "Ébène & Or Fin",
    category: "Haut de Gamme",
    primary: "#232323",
    primaryHover: "#111111",
    secondary: "#C59B27",
    accent: "#D4AF37",
    badgeBg: "#F4F4F4",
    badgeText: "#232323",
    gradient: "from-[#232323] via-[#4A4A4A] to-[#C59B27]",
    previewColor: "#232323",
  },
  {
    id: 8,
    name: "Sauge Divine",
    category: "Nature & Harmonie",
    primary: "#4F7942",
    primaryHover: "#3B5B32",
    secondary: "#B8860B",
    accent: "#87A96B",
    badgeBg: "#F0F6EE",
    badgeText: "#4F7942",
    gradient: "from-[#4F7942] via-[#87A96B] to-[#B8860B]",
    previewColor: "#4F7942",
  },
  {
    id: 9,
    name: "Terre d'Afrique & Ocre",
    category: "Racines & Héritage",
    primary: "#9C4123",
    primaryHover: "#7D331A",
    secondary: "#2E4053",
    accent: "#E59866",
    badgeBg: "#FCF3EB",
    badgeText: "#9C4123",
    gradient: "from-[#9C4123] via-[#E59866] to-[#2E4053]",
    previewColor: "#9C4123",
  },
  {
    id: 10,
    name: "Perle d'Assinie",
    category: "Évasion & Pureté",
    primary: "#2E7D7E",
    primaryHover: "#215B5C",
    secondary: "#C05638",
    accent: "#66C4C5",
    badgeBg: "#EFF9F9",
    badgeText: "#2E7D7E",
    gradient: "from-[#2E7D7E] via-[#66C4C5] to-[#C05638]",
    previewColor: "#2E7D7E",
  },
  {
    id: 11,
    name: "Corail de Grand-Bassam",
    category: "Vibrance & Joie",
    primary: "#B94A3D",
    primaryHover: "#9E3C31",
    secondary: "#16423C",
    accent: "#E88D72",
    badgeBg: "#FCF1EF",
    badgeText: "#B94A3D",
    gradient: "from-[#B94A3D] via-[#E88D72] to-[#16423C]",
    previewColor: "#B94A3D",
  },
  {
    id: 12,
    name: "Bronze Précieux",
    category: "Élégance Ancestrale",
    primary: "#7A5230",
    primaryHover: "#5E3E23",
    secondary: "#1E352F",
    accent: "#D29F68",
    badgeBg: "#F8F3ED",
    badgeText: "#7A5230",
    gradient: "from-[#7A5230] via-[#D29F68] to-[#1E352F]",
    previewColor: "#7A5230",
  },
  {
    id: 13,
    name: "Lavande d'Éden",
    category: "Spiritualité & Paix",
    primary: "#6B5B95",
    primaryHover: "#544677",
    secondary: "#3B4E43",
    accent: "#B8A9C9",
    badgeBg: "#F5F2F9",
    badgeText: "#6B5B95",
    gradient: "from-[#6B5B95] via-[#B8A9C9] to-[#3B4E43]",
    previewColor: "#6B5B95",
  },
  {
    id: 14,
    name: "Ocre de Yamoussoukro",
    category: "Lumière Basilique",
    primary: "#B07D2B",
    primaryHover: "#916521",
    secondary: "#234032",
    accent: "#F3C68F",
    badgeBg: "#FAF5EB",
    badgeText: "#B07D2B",
    gradient: "from-[#B07D2B] via-[#F3C68F] to-[#234032]",
    previewColor: "#B07D2B",
  },
  {
    id: 15,
    name: "Soie & Lin Naturel",
    category: "Minimalisme Pur",
    primary: "#5C6B73",
    primaryHover: "#47535A",
    secondary: "#9C4123",
    accent: "#C2D8B9",
    badgeBg: "#F2F5F7",
    badgeText: "#5C6B73",
    gradient: "from-[#5C6B73] via-[#9DB4C0] to-[#9C4123]",
    previewColor: "#5C6B73",
  },
  {
    id: 16,
    name: "Champagne Royal",
    category: "Festivité & Noces",
    primary: "#8C6D37",
    primaryHover: "#71572A",
    secondary: "#1C3144",
    accent: "#F0E6D2",
    badgeBg: "#F9F6F0",
    badgeText: "#8C6D37",
    gradient: "from-[#8C6D37] via-[#D8C292] to-[#1C3144]",
    previewColor: "#8C6D37",
  },
  {
    id: 17,
    name: "Ambre Chaud & Cannelle",
    category: "Intimité du Foyer",
    primary: "#A0522D",
    primaryHover: "#844223",
    secondary: "#1D3557",
    accent: "#E29578",
    badgeBg: "#FBF3EF",
    badgeText: "#A0522D",
    gradient: "from-[#A0522D] via-[#E29578] to-[#1D3557]",
    previewColor: "#A0522D",
  },
  {
    id: 18,
    name: "Vert Banco & Forêt",
    category: "Fraîcheur & Vie",
    primary: "#2D5A27",
    primaryHover: "#20401B",
    secondary: "#A37A2C",
    accent: "#76A035",
    badgeBg: "#EFF6ED",
    badgeText: "#2D5A27",
    gradient: "from-[#2D5A27] via-[#76A035] to-[#A37A2C]",
    previewColor: "#2D5A27",
  },
  {
    id: 19,
    name: "Vanille & Miel d'Akoupé",
    category: "Douceur Pastorale",
    primary: "#946824",
    primaryHover: "#78531B",
    secondary: "#334E3F",
    accent: "#E6BA55",
    badgeBg: "#FAF6EB",
    badgeText: "#946824",
    gradient: "from-[#946824] via-[#E6BA55] to-[#334E3F]",
    previewColor: "#946824",
  },
  {
    id: 20,
    name: "Nébuleuse Céleste",
    category: "Alliance Éternelle",
    primary: "#3D405B",
    primaryHover: "#2F3147",
    secondary: "#E07A5F",
    accent: "#F2CC8F",
    badgeBg: "#F2F3F8",
    badgeText: "#3D405B",
    gradient: "from-[#3D405B] via-[#81B29A] to-[#E07A5F]",
    previewColor: "#3D405B",
  },
];

export const FONTS_LIST = [
  { id: "cormorant", name: "Cormorant Garamond (Classique & Noble)", fontClass: "font-serif" },
  { id: "playfair", name: "Playfair Display (Élégant & Solennel)", fontClass: "font-serif" },
  { id: "cinzel", name: "Cinzel (Royal & Biblique)", fontClass: "font-serif" },
  { id: "montserrat", name: "Montserrat (Moderne & Épuré)", fontClass: "font-sans" },
  { id: "jakarta", name: "Plus Jakarta Sans (Minimaliste & Clair)", fontClass: "font-sans" },
];

export const DEFAULT_COMMANDMENTS = [
  {
    id: 1,
    text: "Nous prierons ensemble régulièrement.",
    importanceWhy: "Parce que la prière commune invite la présence de Dieu au cœur de nos joies et de nos épreuves.",
    commitmentText: "Nous nous engageons à réserver un moment d'intercession et d'action de grâce à deux chaque semaine.",
  },
  {
    id: 2,
    text: "Nous nous parlerons avec respect.",
    importanceWhy: "Parce que les paroles douces bâtissent le foyer et que le respect préserve l'intimité.",
    commitmentText: "Même sous le coup de la fatigue ou du stress, nous bannissons l'insulte et le mépris.",
  },
  {
    id: 3,
    text: "Nous chercherons à résoudre les conflits plutôt qu'à les gagner.",
    importanceWhy: "Dans le mariage, la victoire d'un seul contre l'autre est une défaite pour l'équipe.",
    commitmentText: "Nous ne laisserons pas le soleil se coucher sur notre colère (Éphésiens 4:26).",
  },
  {
    id: 4,
    text: "Nous serons transparents dans nos décisions financières.",
    importanceWhy: "L'argent est un outil d'édification et non un sujet de secret ou de division.",
    commitmentText: "Toute dépense majeure au-delà de notre seuil sera concertée et validée d'un commun accord.",
  },
  {
    id: 5,
    text: "Nous protégerons notre couple des influences destructrices.",
    importanceWhy: "Notre alliance est un sanctuaire qui doit être gardé avec sagesse et discernement.",
    commitmentText: "Nous ne tolérerons aucune interférence extérieure nuisible à notre unité.",
  },
  {
    id: 6,
    text: "Nous respecterons nos familles sans leur permettre de diriger notre couple.",
    importanceWhy: "Selon Genèse 2:24, l'homme et la femme quittent pour s'attacher et former une nouvelle entité souveraine.",
    commitmentText: "Nous honorerons nos parents tout en gardant l'autonomie sacrée de notre foyer.",
  },
  {
    id: 7,
    text: "Nous prendrons les grandes décisions ensemble.",
    importanceWhy: "Deux valent mieux qu'un car ils ont un bon salaire de leur travail.",
    commitmentText: "Aucune décision engageant le futur de la famille ne sera prise unilatéralement.",
  },
  {
    id: 8,
    text: "Nous cultiverons la fidélité et la confiance.",
    importanceWhy: "La confiance est le socle sur lequel repose tout l'édifice de notre amour.",
    commitmentText: "Nous serons loyaux dans nos regards, nos pensées, nos conversations et nos actes.",
  },
  {
    id: 9,
    text: "Nous prendrons du temps pour notre relation.",
    importanceWhy: "L'amour s'entretient par des rendez-vous intimes, des rires et des moments de complicité.",
    commitmentText: "Nous préserverons nos tête-à-tête romantiques et nos escapades régulières.",
  },
  {
    id: 10,
    text: "Nous placerons Dieu au centre de notre foyer.",
    importanceWhy: "Si l'Éternel ne bâtit la maison, ceux qui la bâtissent travaillent en vain (Psaume 127:1).",
    commitmentText: "Notre maison et nous, nous servirons l'Éternel jour après jour.",
  },
];

export const DEVOTIONAL_THEMES = [
  {
    themeNumber: 1,
    title: "La Fondation : Quitter et s'Attacher",
    scriptureRef: "Genèse 2:24",
    scriptureText: "C'est pourquoi l'homme quittera son père et sa mère, et s'attachera à sa femme, et ils deviendront une seule chair.",
    teaching: "Le mariage commence par une double action spirituelle et émotionnelle : 'quitter' et 's'attacher'. Quitter ne signifie pas abandonner ou manquer d'honneur envers nos parents respectifs, mais établir une nouvelle frontière saine où le couple forme désormais une unité prioritaire. En Côte d'Ivoire, où le tissu familial élargi est très fort, réussir cette étape exige sagesse, bienveillance et fermeté chrétienne.",
    reflection: "Avons-nous clairement défini les limites saines entre l'influence de nos familles respectives et les décisions de notre futur foyer ?",
    coupleQuestion: "Quelle est la chose la plus difficile à 'quitter' pour toi, et comment puis-je t'aider à bâtir notre sanctuaire ?",
    prayerModel: "Seigneur Jésus, pose Ta main sur notre alliance. Accorde-nous la grâce de quitter avec honneur et de nous attacher avec fidélité indéfectible.",
    pastorName: "Pasteur Jean-Marc Kouadio",
    timelinePhase: "J-90",
  },
  {
    themeNumber: 2,
    title: "Les Rôles dans le Couple : Servir et Honorer",
    scriptureRef: "Éphésiens 5:22-33",
    scriptureText: "Maris, aimez vos femmes, comme Christ a aimé l'Église, et s'est livré lui-même pour elle... Femmes, que chacune respecte son mari.",
    teaching: "L'autorité biblique n'est pas une domination patriarcale, mais un sacrifice d'amour à l'image du Christ qui lave les pieds de ses disciples. Le respect de la femme envers son époux libère la force de celui-ci pour protéger et pourvoir, tandis que l'amour sacrificiel de l'homme sécurise le cœur de son épouse.",
    reflection: "Comment manifester concrètement l'amour sacrificiel et le respect mutuel au quotidien dans notre culture ?",
    coupleQuestion: "Dans quels moments te sens-tu le plus aimé(e) et respecté(e) par mes attitudes ?",
    prayerModel: "Père Céleste, apprends-nous à nous soumettre les uns aux autres dans la crainte de Christ. Fais de notre foyer un reflet de Ton amour.",
    pastorName: "Pasteur Emmanuel Brou",
    timelinePhase: "J-60",
  },
  {
    themeNumber: 3,
    title: "La Pureté du Cœur et du Corps",
    scriptureRef: "1 Thessaloniciens 4:3-5",
    scriptureText: "Ce que Dieu veut, c'est votre sanctification ; c'est que vous vous absteniez de l'impudicité ; c'est que chacun de vous sache posséder son corps dans la sainteté et l'honnêteté.",
    teaching: "La pureté avant le mariage n'est pas une contrainte légaliste, mais un cadeau d'honneur que nous offrons à Dieu et à notre futur conjoint. Garder notre sanctification préserve l'alliance de culpabilité et permet d'entrer dans la nuit de noces avec une conscience pure et bénie.",
    reflection: "Quels mécanismes de protection et de prière avons-nous mis en place pour honorer Dieu jusqu'au jour de la bénédiction nuptiale ?",
    coupleQuestion: "Y a-t-il des craintes ou des sujets intimes dont nous devons parler ouvertement dans la grâce et la vérité ?",
    prayerModel: "Seigneur Saint, sanctifie nos regards, nos cœurs et nos corps. Remplis-nous du Saint-Esprit pour marcher dans l'intégrité jusqu'au Jour J.",
    pastorName: "Pasteur Époux Yao",
    timelinePhase: "J-60",
  },
  {
    themeNumber: 4,
    title: "La Communication : Vaincre les Conflits",
    scriptureRef: "Éphésiens 4:26-29",
    scriptureText: "Si vous vous mettez en colère, ne péchez point ; que le soleil ne se couche pas sur votre colère... Qu'il ne sorte de votre bouche aucune parole mauvaise.",
    teaching: "Les désaccords sont inévitables dans toute relation humaine, mais la destruction est évitable. La clé chrétienne est d'écouter activement avant de répondre, d'attaquer le problème et jamais la personne, et de refuser le silence punitif ou la rancœur accumulée.",
    reflection: "Comment gérons-nous nos frustrations lorsqu'un préparatif du mariage ne se déroule pas comme prévu ?",
    coupleQuestion: "Quel est mon réflexe en cas de tension, et comment puis-je mieux communiquer avec douceur ?",
    prayerModel: "Seigneur, mets une garde à ma bouche, veille sur la porte de mes lèvres. Que nos échanges guérissent et unissent.",
    pastorName: "Pasteure Grace N'Guessan",
    timelinePhase: "J-30",
  },
  {
    themeNumber: 5,
    title: "L'Argent et la Gestion Bénie",
    scriptureRef: "Malachie 3:10 & Proverbes 3:9-10",
    scriptureText: "Honore l'Éternel avec tes biens, et avec les prémices de tout ton revenu : alors tes greniers seront remplis d'abondance.",
    teaching: "Dans le couple chrétien, les finances ne sont plus 'mon argent' et 'ton argent', mais 'les ressources que Dieu nous a confiées'. La fidélité dans la dîme, la transparence budgétaire totale et l'accord mutuel pour toute dépense importante (au-delà de 50 000 FCFA) scellent la bénédiction financière du foyer.",
    reflection: "Pratiquons-nous la transparence totale sur nos dettes, nos revenus et notre vision budgétaire d'après-mariage ?",
    coupleQuestion: "Quel est notre plan d'épargne pour le premier loyer et le fonds de secours du couple ?",
    prayerModel: "Éternel Jiré, Tu es notre pourvoyeur. Nous Te consacrons nos salaires, nos affaires et nos dépenses. Que notre foyer soit généreux et sage.",
    pastorName: "Pasteur Stéphane Bamba",
    timelinePhase: "J-30",
  },
  {
    themeNumber: 6,
    title: "La Belle-Famille : Honneur et Sagesse",
    scriptureRef: "Épouse 1:16-17 & Proverbes 11:2",
    scriptureText: "Où tu iras j'irai, où tu demeureras je demeurerai ; ton peuple sera mon peuple, et ton Dieu sera mon Dieu.",
    teaching: "Aimer son conjoint, c'est aussi apprendre à aimer et honorer les parents qui lui ont donné la vie. Toutefois, les traditions culturelles (dot, réunions de famille) doivent s'aligner sur la parole de Dieu. La sagesse consiste à honorer sans idolâtrer, et à protéger l'intimité du foyer sans offenser.",
    reflection: "Comment équilibrons-nous l'honneur dû à nos parents et la primauté de notre nouveau couple ?",
    coupleQuestion: "Quelles attentes de nos familles respectives devons-nous clarifier ensemble en toute sérénité ?",
    prayerModel: "Seigneur, donne-nous l'amour surnaturel pour nos belles-familles. Fais de nous des artisans de paix et de respect.",
    pastorName: "Pasteur Félix Amani",
    timelinePhase: "J-14",
  },
  {
    themeNumber: 7,
    title: "La Mission du Foyer : Servir l'Éternel",
    scriptureRef: "Josué 24:15",
    scriptureText: "Moi et ma maison, nous servirons l'Éternel.",
    teaching: "Le mariage chrétien n'est pas seulement fait pour notre propre bonheur, mais pour la gloire de Dieu et le service de notre génération. Un couple uni en Christ devient un refuge pour les affligés, un exemple pour la jeunesse et une lumière dans la société ivoirienne.",
    reflection: "Quelle sera la signature spirituelle de notre maison une fois mariés ?",
    coupleQuestion: "De quelle manière souhaitons-nous servir Dieu ensemble au sein de notre église et de notre communauté ?",
    prayerModel: "Père Tout-Puissant, consacre notre couple comme un instrument d'espérance et de lumière. Que notre union glorifie Ton saint nom pour toujours.",
    pastorName: "Pasteur Jean-Marc Kouadio",
    timelinePhase: "J-7",
  },
];

