export interface TemplateDefinition {
  id: string;
  name: string;
  category: string;
  description: string;
  primary: string;
  secondary: string;
  accent: string;
  badgeBg: string;
  badgeText: string;
  surfaceBg: string;
  cardBg: string;
  borderStyle: string;
  fontClass: string;
  styleTags: string[];
}

export const INVITATION_TEMPLATES_20: TemplateDefinition[] = [
  {
    id: "classique_elegant",
    name: "Classique Élégant",
    category: "Intemporel",
    description: "Lignes pures, double filet or royal et typographie majestueuse.",
    primary: "#B8860B",
    secondary: "#1E293B",
    accent: "#E5C158",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-800",
    surfaceBg: "bg-[#FFFDF9]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#D4AF37]",
    fontClass: "font-serif",
    styleTags: ["Noble", "Intemporel", "Prestige"],
  },
  {
    id: "minimaliste",
    name: "Minimaliste",
    category: "Épuré",
    description: "Grands espaces respirants, pureté du blanc et typographie contemporaine.",
    primary: "#334155",
    secondary: "#64748B",
    accent: "#94A3B8",
    badgeBg: "bg-slate-100",
    badgeText: "text-slate-800",
    surfaceBg: "bg-[#F8FAFC]",
    cardBg: "bg-white",
    borderStyle: "border border-slate-200",
    fontClass: "font-sans",
    styleTags: ["Moderne", "Clair", "Sobre"],
  },
  {
    id: "terracotta_or",
    name: "Terracotta & Or",
    category: "Signature Wedding Mood",
    description: "Chaleur ivoirienne, terracotta authentique et détails dorés délicats.",
    primary: "#C05638",
    secondary: "#1E3A2F",
    accent: "#D4AF37",
    badgeBg: "bg-orange-50",
    badgeText: "text-[#C05638]",
    surfaceBg: "bg-[#FCFAF7]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#C05638]/40",
    fontClass: "font-serif",
    styleTags: ["Ivoirien", "Chaleureux", "Emblématique"],
  },
  {
    id: "blanc_or",
    name: "Blanc & Or",
    category: "Lumière & Noblesse",
    description: "Fond blanc glacé étincelant avec accents dorés subtils.",
    primary: "#A37A2C",
    secondary: "#232323",
    accent: "#E8C872",
    badgeBg: "bg-[#FFFDF0]",
    badgeText: "text-[#846220]",
    surfaceBg: "bg-[#FFFFFF]",
    cardBg: "bg-[#FFFDF9]",
    borderStyle: "border-2 border-[#D4AF37]/60",
    fontClass: "font-serif",
    styleTags: ["Lumière", "Élégance", "Or fin"],
  },
  {
    id: "floral",
    name: "Floral",
    category: "Romantique",
    description: "Douces arabesques florales, rose poudré et champagne.",
    primary: "#A65B6F",
    secondary: "#34495E",
    accent: "#D9A066",
    badgeBg: "bg-rose-50",
    badgeText: "text-rose-800",
    surfaceBg: "bg-[#FFFBFB]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#A65B6F]/30",
    fontClass: "font-serif",
    styleTags: ["Délicat", "Fleurs", "Poétique"],
  },
  {
    id: "arche",
    name: "Arche",
    category: "Architectural",
    description: "Composition en arche sacrée, symbole d'alliance et de sanctuaire.",
    primary: "#7A5230",
    secondary: "#1E352F",
    accent: "#D29F68",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-900",
    surfaceBg: "bg-[#FCFAF7]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#B37D28]/40 rounded-t-full",
    fontClass: "font-serif",
    styleTags: ["Arche", "Symbole", "Harmonie"],
  },
  {
    id: "medaillon",
    name: "Médaillon",
    category: "Joaillerie",
    description: "Médaillon central raffiné, hommage aux bijoux d'alliance.",
    primary: "#8C6D37",
    secondary: "#1C3144",
    accent: "#D8C292",
    badgeBg: "bg-amber-50/80",
    badgeText: "text-amber-900",
    surfaceBg: "bg-[#FAF7F2]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#D4AF37]/60",
    fontClass: "font-serif",
    styleTags: ["Sceau", "Bijou", "Précieux"],
  },
  {
    id: "polaroid_elegant",
    name: "Polaroid Élégant",
    category: "Instantané",
    description: "Cadre blanc texturé avec signature calligraphiée en bas de carte.",
    primary: "#4F7942",
    secondary: "#232323",
    accent: "#87A96B",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-800",
    surfaceBg: "bg-[#F8FAFC]",
    cardBg: "bg-white",
    borderStyle: "border-4 border-white shadow-lg",
    fontClass: "font-sans",
    styleTags: ["Authentique", "Souvenir", "Chaleureux"],
  },
  {
    id: "carte_postale",
    name: "Carte Postale",
    category: "Correspondance",
    description: "Esprit faire-part voyage avec timbre doré et séparation d'écriture.",
    primary: "#9C4123",
    secondary: "#2E4053",
    accent: "#E59866",
    badgeBg: "bg-orange-50",
    badgeText: "text-orange-900",
    surfaceBg: "bg-[#FCFAF7]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-dashed border-[#C05638]/40",
    fontClass: "font-serif",
    styleTags: ["Timbre", "Message", "Postale"],
  },
  {
    id: "passeport",
    name: "Passeport",
    category: "Voyage d'une Vie",
    description: "Livret de voyage nuptial avec monogramme royal, visa d'amour et sceau officiel.",
    primary: "#1E3A2F",
    secondary: "#C05638",
    accent: "#D4AF37",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-900",
    surfaceBg: "bg-[#F8FAF9]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#1E3A2F]/40 shadow-xl",
    fontClass: "font-serif",
    styleTags: ["Visa", "Passeport", "Aventure"],
  },
  {
    id: "boarding_pass",
    name: "Boarding Pass",
    category: "Embarquement",
    description: "Véritable carte d'embarquement pour le mariage : Destination Bonheur éternel.",
    primary: "#1B3B6F",
    secondary: "#C05638",
    accent: "#E0A96D",
    badgeBg: "bg-blue-50",
    badgeText: "text-blue-900",
    surfaceBg: "bg-[#F7FAFC]",
    cardBg: "bg-white",
    borderStyle: "border border-blue-200 shadow-md",
    fontClass: "font-sans",
    styleTags: ["Vol", "Embarquement", "Billet"],
  },
  {
    id: "ticket",
    name: "Ticket",
    category: "Célébration",
    description: "Ticket d'entrée VIP découpé sur les côtés avec perforation graphique.",
    primary: "#B94A3D",
    secondary: "#16423C",
    accent: "#E88D72",
    badgeBg: "bg-red-50",
    badgeText: "text-red-900",
    surfaceBg: "bg-[#FCFAF7]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-dashed border-[#B94A3D]/40",
    fontClass: "font-mono",
    styleTags: ["Événement", "Billet VIP", "Perforé"],
  },
  {
    id: "carnet_de_voyage",
    name: "Carnet de Voyage",
    category: "Journal de Bord",
    description: "Pages reliées, croquis doux et notes personnelles des fiancés.",
    primary: "#7A5230",
    secondary: "#232323",
    accent: "#D29F68",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-800",
    surfaceBg: "bg-[#FAF6EE]",
    cardBg: "bg-white",
    borderStyle: "border-l-4 border-l-[#7A5230] border-y border-r border-stone-200",
    fontClass: "font-serif",
    styleTags: ["Carnet", "Histoire", "Souvenirs"],
  },
  {
    id: "editorial",
    name: "Éditorial",
    category: "Haute Couture",
    description: "Mise en page magazine d'art, typographie géante et colonnes aérées.",
    primary: "#232323",
    secondary: "#B8860B",
    accent: "#D4AF37",
    badgeBg: "bg-stone-100",
    badgeText: "text-stone-900",
    surfaceBg: "bg-white",
    cardBg: "bg-white",
    borderStyle: "border-y border-stone-900/80",
    fontClass: "font-serif",
    styleTags: ["Magazine", "Typo XXL", "Épure"],
  },
  {
    id: "africain_chic",
    name: "Africain Chic",
    category: "Héritage Ivoirien",
    description: "Frises géométriques subtiles inspirées du pagne kita et de l'or d'Akan.",
    primary: "#9C4123",
    secondary: "#145A32",
    accent: "#B37D28",
    badgeBg: "bg-orange-50",
    badgeText: "text-orange-900",
    surfaceBg: "bg-[#FCFAF7]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#B37D28]/60 shadow-lg",
    fontClass: "font-serif",
    styleTags: ["Kita", "Art Akan", "Tradition"],
  },
  {
    id: "spirituel",
    name: "Spirituel",
    category: "Foi & Alliance",
    description: "Centré sur la bénédiction nuptiale, croix délicate et verset d'honneur.",
    primary: "#B07D2B",
    secondary: "#145A32",
    accent: "#C05638",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-900",
    surfaceBg: "bg-[#FAF7F2]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#B07D2B]/40",
    fontClass: "font-serif",
    styleTags: ["Verset", "Croix", "Grâce"],
  },
  {
    id: "monogramme",
    name: "Monogramme",
    category: "Sceau Impérial",
    description: "Initiales entrelacées majestueuses placées au centre d'un blason royal.",
    primary: "#C05638",
    secondary: "#B8860B",
    accent: "#E5C158",
    badgeBg: "bg-[#FFFDF0]",
    badgeText: "text-[#C05638]",
    surfaceBg: "bg-[#FCFAF7]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#D4AF37]/70",
    fontClass: "font-serif",
    styleTags: ["Blason", "Initiales", "Royal"],
  },
  {
    id: "photo_pleine_couverture",
    name: "Photo Pleine Couverture",
    category: "Immersif",
    description: "Grande photo plein écran avec typographie en transparence verre dépoli.",
    primary: "#FFFFFF",
    secondary: "#C05638",
    accent: "#D4AF37",
    badgeBg: "bg-white/80",
    badgeText: "text-stone-900",
    surfaceBg: "bg-stone-50",
    cardBg: "bg-white",
    borderStyle: "border-none shadow-xl",
    fontClass: "font-serif",
    styleTags: ["Grand format", "Verre dépoli", "Visuel"],
  },
  {
    id: "diptyque",
    name: "Diptyque",
    category: "Double Volet",
    description: "Harmonie en deux volets équilibrés : les mariés et leur engagement.",
    primary: "#2E7D7E",
    secondary: "#C05638",
    accent: "#E5C158",
    badgeBg: "bg-teal-50",
    badgeText: "text-teal-900",
    surfaceBg: "bg-[#F6FAF9]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#2E7D7E]/40",
    fontClass: "font-serif",
    styleTags: ["Deux volets", "Équilibre", "Harmonie"],
  },
  {
    id: "collage",
    name: "Collage",
    category: "Galerie d'Art",
    description: "Composition artistique rythmée réunissant plusieurs facettes du couple.",
    primary: "#6B5B95",
    secondary: "#3B4E43",
    accent: "#B8A9C9",
    badgeBg: "bg-purple-50",
    badgeText: "text-purple-900",
    surfaceBg: "bg-[#FAF8FC]",
    cardBg: "bg-white",
    borderStyle: "border-2 border-[#6B5B95]/30",
    fontClass: "font-serif",
    styleTags: ["Art", "Mosaïque", "Créatif"],
  },
];

export interface PhotoFrameDefinition {
  id: string;
  name: string;
  description: string;
  containerClass: string;
  iconName: string;
}

export const PHOTO_FRAMES_20: PhotoFrameDefinition[] = [
  { id: "rectangle_classique", name: "Rectangle Classique", description: "Bords nets et équilibrés", containerClass: "w-full max-w-sm h-64 sm:h-80 rounded-2xl mx-auto shadow-md border-2 border-white", iconName: "Square" },
  { id: "portrait_elegant", name: "Portrait Élégant", description: "Format vertical noble 3:4", containerClass: "w-56 sm:w-68 h-80 sm:h-96 rounded-2xl mx-auto shadow-lg border-2 border-white", iconName: "RectangleVertical" },
  { id: "pleine_couverture", name: "Photo Pleine Couverture", description: "Couverture immersive grand format", containerClass: "w-full h-80 sm:h-[420px] rounded-3xl shadow-xl", iconName: "Maximize2" },
  { id: "ronde", name: "Photo Ronde", description: "Cercle parfait médaillon", containerClass: "w-48 h-48 sm:w-64 sm:h-64 rounded-full mx-auto shadow-xl border-4 border-white", iconName: "Circle" },
  { id: "ovale", name: "Photo Ovale", description: "Courbe douce et classique", containerClass: "w-52 sm:w-64 h-72 sm:h-88 rounded-[50%] mx-auto shadow-xl border-4 border-white", iconName: "CircleDot" },
  { id: "arche", name: "Arche", description: "Sommet en dôme romantique", containerClass: "w-56 sm:w-68 h-80 sm:h-96 rounded-t-full rounded-b-2xl mx-auto shadow-2xl border-4 border-white", iconName: "Compass" },
  { id: "arche_inversee", name: "Arche Inversée", description: "Courbe suspendue vers le bas", containerClass: "w-56 sm:w-68 h-80 sm:h-96 rounded-b-full rounded-t-2xl mx-auto shadow-2xl border-4 border-white", iconName: "ChevronDown" },
  { id: "cadre_double", name: "Cadre Double", description: "Bordure double avec passe-partout", containerClass: "w-full max-w-sm h-64 sm:h-80 rounded-2xl mx-auto p-2.5 bg-white border border-stone-200 shadow-xl", iconName: "Layers" },
  { id: "cadre_dore", name: "Cadre Doré", description: "Filet d'or précieux 18K", containerClass: "w-full max-w-sm h-64 sm:h-80 rounded-2xl mx-auto p-2 bg-[#FFFDF0] border-2 border-[#D4AF37] shadow-xl", iconName: "Sparkles" },
  { id: "cadre_terracotta", name: "Cadre Terracotta", description: "Terre cuite ivoirienne raffinée", containerClass: "w-full max-w-sm h-64 sm:h-80 rounded-2xl mx-auto p-2 bg-[#FCFAF7] border-2 border-[#C05638] shadow-xl", iconName: "Flame" },
  { id: "polaroid_elegant", name: "Polaroid Élégant", description: "Marge blanche large en bas de photo", containerClass: "w-56 sm:w-72 pt-3 px-3 pb-12 bg-white rounded-xl shadow-2xl border border-stone-200 mx-auto", iconName: "Camera" },
  { id: "carte_postale", name: "Carte Postale", description: "Bordure dentelée timbre postale", containerClass: "w-full max-w-md h-60 sm:h-72 p-2 bg-[#FAF6EE] rounded-2xl border-2 border-dashed border-[#B37D28] shadow-md mx-auto", iconName: "Mail" },
  { id: "passeport", name: "Passeport", description: "Format photo d'identité d'alliance", containerClass: "w-48 sm:w-56 h-64 sm:h-72 rounded-xl border-2 border-[#1E3A2F] p-1.5 bg-white shadow-xl mx-auto", iconName: "FileText" },
  { id: "boarding_pass", name: "Boarding Pass", description: "Volet d'embarquement billet aérien", containerClass: "w-full max-w-md h-52 sm:h-64 rounded-2xl border-2 border-blue-300 p-2 bg-white shadow-md mx-auto", iconName: "Send" },
  { id: "ticket_decoupe", name: "Ticket Découpé", description: "Encoches latérales pour billet", containerClass: "w-full max-w-sm h-56 sm:h-68 rounded-2xl border-2 border-[#B94A3D] p-2 bg-white shadow-md mx-auto relative", iconName: "Tag" },
  { id: "fenetre", name: "Fenêtre", description: "Croisée vitrée à arcades", containerClass: "w-56 sm:w-68 h-76 sm:h-92 rounded-t-3xl border-4 border-stone-100 shadow-xl mx-auto", iconName: "Layout" },
  { id: "medaillon", name: "Médaillon", description: "Cercle orné d'un ruban d'or", containerClass: "w-52 h-52 sm:w-68 sm:h-68 rounded-full border-4 border-[#D4AF37] p-1 bg-white shadow-2xl mx-auto", iconName: "Award" },
  { id: "coeur_elegant", name: "Cœur Élégant", description: "Silhouette romantique épurée", containerClass: "w-56 sm:w-68 h-64 sm:h-76 rounded-3xl border-2 border-rose-300 shadow-lg mx-auto", iconName: "Heart" },
  { id: "diptyque", name: "Diptyque", description: "Double portrait côte à côte", containerClass: "w-full max-w-md h-56 sm:h-72 rounded-2xl grid grid-cols-2 gap-2 p-1.5 bg-white border border-stone-200 shadow-lg mx-auto", iconName: "Columns2" },
  { id: "collage", name: "Collage", description: "Composition mosaïque créative", containerClass: "w-full max-w-md h-64 sm:h-80 rounded-2xl p-2 bg-white border border-stone-200 shadow-xl mx-auto", iconName: "Grid" },
];

