"use client"; import { useEffect, useState } from "react"; import FileUpload from "@/components/admin/FileUpload";
const SERVINGS=[100,200,300,400,500,1000];
export default function Page(){
  const [list,setList]=useState<any[]>([]); const [form,setForm]=useState<any>({name:"",servings:100,dishes:[],cover_image:"",currency:"XOF",order_index:0});
  const [dish,setDish]=useState({name:"",quantity:1,unit_price:0});
  async function load(){ const r=await fetch("/api/admin/menus"); const j=await r.json(); setList(j.menus||[]); }
  useEffect(()=>{load();},[]);
  const total=form.dishes.reduce((s:number,d:any)=>s+d.quantity*d.unit_price,0);
  async function save(){ await fetch("/api/admin/menus",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form})}); setForm({name:"",servings:100,dishes:[],cover_image:"",currency:"XOF",order_index:0}); load(); }
  return (<div className="p-6 space-y-6">
    <div><h1 className="text-2xl font-bold text-[#800020]">Menus Africains - par 100 à 1000 pers</h1><p className="text-sm text-gray-500 mt-1">Créez vos menus avec <b>photo depuis disque</b>. Ajoutez chaque plat avec quantité et prix unitaire, le <b>total se calcule tout seul</b> par le système.</p></div>
    <div className="bg-white p-4 rounded-xl border space-y-4">
      <div className="grid grid-cols-3 gap-2"><div><label className="text-xs font-semibold">Nom du menu *</label><input className="w-full border p-2 rounded mt-1" placeholder="Ex: Menu Attiéké Poisson" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="text-xs font-semibold">Nombre de personnes *</label><select className="w-full border p-2 rounded mt-1" value={form.servings} onChange={e=>setForm({...form,servings:Number(e.target.value)})}>{SERVINGS.map(s=><option key={s} value={s}>{s} personnes</option>)}</select><p className="text-[11px] text-gray-400">Choisissez 100, 200, 300, 400, 500 ou 1000.</p></div><div><label className="text-xs font-semibold">Devise</label><input className="w-full border p-2 rounded mt-1" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><p className="text-[11px] text-gray-400">XOF, USD, EUR selon pays.</p></div></div>
      <FileUpload label="Photo du menu - depuis disque (Storage) *" folder="menus" accept="image/*" value={form.cover_image} onUploaded={url=>setForm({...form,cover_image:url})}/>
      <div className="border p-3 rounded-lg space-y-2 bg-gray-50"><p className="font-semibold text-sm">Plats / Ingrédients - Total auto: <span className="text-[#800020]">{total} {form.currency}</span></p><p className="text-[11px] text-gray-400">Ajoutez chaque plat : nom, quantité, prix unitaire. Le total se met à jour tout seul.</p><div className="grid grid-cols-4 gap-2"><input className="border p-2 rounded" placeholder="Nom plat - ex: Poulet" value={dish.name} onChange={e=>setDish({...dish,name:e.target.value})}/><input type="number" className="border p-2 rounded" placeholder="Qté - ex: 10" value={dish.quantity} onChange={e=>setDish({...dish,quantity:Number(e.target.value)})}/><input type="number" className="border p-2 rounded" placeholder="Prix unit - ex: 5000" value={dish.unit_price} onChange={e=>setDish({...dish,unit_price:Number(e.target.value)})}/><button onClick={()=>{if(dish.name){setForm({...form,dishes:[...form.dishes,dish]}); setDish({name:"",quantity:1,unit_price:0});}}} className="bg-[#800020] text-white rounded text-sm">+ Ajouter plat</button></div><ul className="text-xs space-y-1">{form.dishes.map((d:any,i:number)=><li key={i} className="flex justify-between bg-white p-1 rounded"><span>{d.name} x{d.quantity}</span><span>{d.quantity*d.unit_price} {form.currency}</span></li>)}</ul></div>
      <button onClick={save} className="bg-[#D4AF37] text-white px-6 py-2 rounded font-bold">Enregistrer Menu {total>0?`(${total} ${form.currency})`:""}</button>
    </div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{list.map((m:any)=><div key={m.id} className="bg-white border rounded-xl overflow-hidden"><img src={m.cover_image} className="h-32 w-full object-cover bg-gray-100"/><div className="p-2 text-sm"><b>{m.name}</b> - {m.servings} pers<br/><span className="font-bold text-[#800020]">{m.total_price} {m.currency}</span></div></div>)}</div>
  </div>);
}