"use client"; import { useEffect, useState } from "react"; import FileUpload from "@/components/admin/FileUpload";
const TYPES=[{id:"traditionnel",label:"Traditionnel",desc:"Mariage africain classique"},{id:"moderne",label:"Moderne",desc:"Style contemporain"},{id:"petit-budget",label:"Petit Budget",desc:"Économique mais chic"},{id:"grand-standing",label:"Grand Standing",desc:"Luxe et prestige"},{id:"mixte",label:"Mixte",desc:"Traditionnel + Moderne"},{id:"royal",label:"Royal",desc:"Très haut de gamme"}];
export default function Page(){
  const [list,setList]=useState<any[]>([]); const [form,setForm]=useState<any>({type:"traditionnel",title:"",description:"",cover_image:"",video_entree_url:"",video_ballet_url:"",order_index:0,checklist:[],musiques:[]});
  const [checkInput,setCheckInput]=useState(""); const [musiqueInput,setMusiqueInput]=useState("");
  async function load(){ const r=await fetch("/api/admin/modeles"); const j=await r.json(); setList(j.modeles||[]); }
  useEffect(()=>{load();},[]);
  async function save(){ await fetch("/api/admin/modeles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); setForm({type:"traditionnel",title:"",description:"",cover_image:"",video_entree_url:"",video_ballet_url:"",order_index:0,checklist:[],musiques:[]}); load(); }
  return (<div className="p-6 space-y-6">
    <div><h1 className="text-2xl font-bold text-[#800020]">Modèles Mariage - 6 types</h1><p className="text-sm text-gray-500 mt-1">Créez des modèles prêts à l&apos;emploi pour les couples. Chaque modèle a une <b>cover depuis disque</b>, 2 vidéos YouTube (entrée + ballet), une checklist et des musiques.</p></div>
    <div className="bg-white p-4 rounded-xl border space-y-4">
      <div className="grid grid-cols-2 gap-2"><div><label className="text-xs font-semibold">Type de mariage *</label><select className="w-full border p-2 rounded mt-1" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(t=><option key={t.id} value={t.id}>{t.label} - {t.desc}</option>)}</select><p className="text-[11px] text-gray-400 mt-1">Le type détermine le style proposé aux couples.</p></div><div><label className="text-xs font-semibold">Ordre</label><input type="number" className="w-full border p-2 rounded mt-1" placeholder="0 = premier" value={form.order_index} onChange={e=>setForm({...form,order_index:Number(e.target.value)})}/></div></div>
      <div><input className="w-full border p-2 rounded" placeholder="Titre du modèle - ex: Royal Baoulé" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><p className="text-[11px] text-gray-400">Titre visible par les couples.</p></div>
      <div><textarea className="w-full border p-2 rounded" placeholder="Description - expliquez le style" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><p className="text-[11px] text-gray-400">Description courte du modèle.</p></div>
      <FileUpload label="Cover Image - Photo principale depuis disque (Storage) *" folder="modeles" accept="image/*" value={form.cover_image} onUploaded={url=>setForm({...form,cover_image:url})}/>
      <div className="grid grid-cols-2 gap-2"><div><input className="w-full border p-2 rounded" placeholder="Vidéo Entrée YouTube - https://youtu.be/..." value={form.video_entree_url} onChange={e=>setForm({...form,video_entree_url:e.target.value})}/><p className="text-[11px] text-gray-400">Vidéo de l&apos;entrée des mariés.</p></div><div><input className="w-full border p-2 rounded" placeholder="Vidéo Ballet YouTube - https://youtu.be/..." value={form.video_ballet_url} onChange={e=>setForm({...form,video_ballet_url:e.target.value})}/><p className="text-[11px] text-gray-400">Vidéo du ballet / danse.</p></div></div>
      <div className="border p-3 rounded-lg space-y-2 bg-gray-50"><p className="font-semibold text-sm">Checklist - Étapes à suivre</p><p className="text-[11px] text-gray-400">Ajoutez chaque tâche que le couple doit faire pour ce modèle.</p><div className="flex gap-2"><input className="flex-1 border p-2 rounded" value={checkInput} onChange={e=>setCheckInput(e.target.value)} placeholder="Ex: Réserver la salle"/><button onClick={()=>{if(checkInput){setForm({...form,checklist:[...form.checklist,checkInput]}); setCheckInput("");}}} className="bg-gray-200 px-3 rounded text-sm">+ Ajouter</button></div><p className="text-xs">{form.checklist.join(" • ")}</p></div>
      <div className="border p-3 rounded-lg space-y-2 bg-gray-50"><p className="font-semibold text-sm">Musiques conseillées</p><p className="text-[11px] text-gray-400">Lien YouTube ou titre de chanson.</p><div className="flex gap-2"><input className="flex-1 border p-2 rounded" value={musiqueInput} onChange={e=>setMusiqueInput(e.target.value)} placeholder="Ex: https://youtu.be/... ou Josey -..."/><button onClick={()=>{if(musiqueInput){setForm({...form,musiques:[...form.musiques,musiqueInput]}); setMusiqueInput("");}}} className="bg-gray-200 px-3 rounded text-sm">+ Ajouter</button></div><p className="text-xs">{form.musiques.join(" • ")}</p></div>
      <button onClick={save} className="bg-[#D4AF37] text-white px-6 py-2 rounded font-bold">Ajouter Modèle</button>
    </div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{list.map((m:any)=><div key={m.id} className="bg-white border rounded-xl overflow-hidden"><img src={m.cover_image} className="h-40 w-full object-cover bg-gray-100"/><div className="p-2"><b>{m.title}</b><br/><span className="text-xs bg-[#800020] text-white px-2 py-0.5 rounded">{m.type}</span></div></div>)}</div>
  </div>);
}